name: CI/CD Pipeline

on:
  push:
    branches: [main]  # or 'master' if you're using that

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.shivam7000}}
          password: ${{ secrets.1@Shivam!}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shivam7000/my-vite-app:latest
